name = "RolePlayMod"; 									// name 
picture = "BP1\images\logo/RPmod.edds";		// картинка в развернутом описании
logoSmall = "BP1\images\logo\RPmod.edds";		// значок рядом с именем мода, когда описание не развернуто
logo = "BP1\images\logo/RPmod.edds";			// логотип под игровым меню
logoOver = "BP1\images\logo\RPmod.edds";		// при наведении мыши на логотип
tooltip = "RolePlayMod";						// подсказка при наведении мыши
overview = ""; 					// overview
action = "";				// link
author = "Rufik, Beliy";										// author
version = "1.0";										// version