name = "Forced First Person Combat";
picture = "ForcedFirstPersonCombat/logos/modIcon.tga";
logoSmall = "ForcedFirstPersonCombat/logos/modIconSmall.tga";
logo = "ForcedFirstPersonCombat/logos/modIconSmall.tga";
logoOver = "ForcedFirstPersonCombat/logos/mocIcon.tga";
tooltip = "Locks the camera to first person with a weapon out!";
overview = "Forced First Person Combat locks the players camera to the first person perspective if they're holding a weapon.";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=1787304576";
author = "Cooltrain";
version = "1.2";