name = "MyDayZ Dingo Truck";
author = "LaGTeK";
version = "1.05";
overview = "This mod bring an Dingo Truck to the game";		 					// description
action = "https://discord.me/mydayz";						// link
tooltip = "MyDayz Dingo";
picture = "MDZ_Dingo\Images\logo-Dingo.paa";							// normal
logoSmall = "MDZ_Dingo\Images\logo-Dingo.paa";							// small
logo = "MDZ_Dingo\Images\logo-Dingo.paa";								// small
logoOver = "MDZ_Dingo\Images\logo-Dingo.paa";							// overview